// Generated by gencpp from file iamech_ros/WPLCRequest.msg
// DO NOT EDIT!


#ifndef IAMECH_ROS_MESSAGE_WPLCREQUEST_H
#define IAMECH_ROS_MESSAGE_WPLCREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iamech_ros
{
template <class ContainerAllocator>
struct WPLCRequest_
{
  typedef WPLCRequest_<ContainerAllocator> Type;

  WPLCRequest_()
    : name()
    , value(0)  {
    }
  WPLCRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::iamech_ros::WPLCRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iamech_ros::WPLCRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WPLCRequest_

typedef ::iamech_ros::WPLCRequest_<std::allocator<void> > WPLCRequest;

typedef boost::shared_ptr< ::iamech_ros::WPLCRequest > WPLCRequestPtr;
typedef boost::shared_ptr< ::iamech_ros::WPLCRequest const> WPLCRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iamech_ros::WPLCRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iamech_ros::WPLCRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iamech_ros::WPLCRequest_<ContainerAllocator1> & lhs, const ::iamech_ros::WPLCRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iamech_ros::WPLCRequest_<ContainerAllocator1> & lhs, const ::iamech_ros::WPLCRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iamech_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iamech_ros::WPLCRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iamech_ros::WPLCRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iamech_ros::WPLCRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65fedc7a0cbfb8db035e46194a350bf1";
  }

  static const char* value(const ::iamech_ros::WPLCRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65fedc7a0cbfb8dbULL;
  static const uint64_t static_value2 = 0x035e46194a350bf1ULL;
};

template<class ContainerAllocator>
struct DataType< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iamech_ros/WPLCRequest";
  }

  static const char* value(const ::iamech_ros::WPLCRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 value\n"
;
  }

  static const char* value(const ::iamech_ros::WPLCRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WPLCRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iamech_ros::WPLCRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iamech_ros::WPLCRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAMECH_ROS_MESSAGE_WPLCREQUEST_H
