// Generated by gencpp from file iamech_ros/WPLCResponse.msg
// DO NOT EDIT!


#ifndef IAMECH_ROS_MESSAGE_WPLCRESPONSE_H
#define IAMECH_ROS_MESSAGE_WPLCRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iamech_ros
{
template <class ContainerAllocator>
struct WPLCResponse_
{
  typedef WPLCResponse_<ContainerAllocator> Type;

  WPLCResponse_()
    {
    }
  WPLCResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::iamech_ros::WPLCResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iamech_ros::WPLCResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WPLCResponse_

typedef ::iamech_ros::WPLCResponse_<std::allocator<void> > WPLCResponse;

typedef boost::shared_ptr< ::iamech_ros::WPLCResponse > WPLCResponsePtr;
typedef boost::shared_ptr< ::iamech_ros::WPLCResponse const> WPLCResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iamech_ros::WPLCResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iamech_ros::WPLCResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace iamech_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iamech_ros::WPLCResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iamech_ros::WPLCResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iamech_ros::WPLCResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::iamech_ros::WPLCResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iamech_ros/WPLCResponse";
  }

  static const char* value(const ::iamech_ros::WPLCResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::iamech_ros::WPLCResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WPLCResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iamech_ros::WPLCResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::iamech_ros::WPLCResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IAMECH_ROS_MESSAGE_WPLCRESPONSE_H
