// Generated by gencpp from file iamech_ros/WPLC.msg
// DO NOT EDIT!


#ifndef IAMECH_ROS_MESSAGE_WPLC_H
#define IAMECH_ROS_MESSAGE_WPLC_H

#include <ros/service_traits.h>


#include <iamech_ros/WPLCRequest.h>
#include <iamech_ros/WPLCResponse.h>


namespace iamech_ros
{

struct WPLC
{

typedef WPLCRequest Request;
typedef WPLCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WPLC
} // namespace iamech_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::iamech_ros::WPLC > {
  static const char* value()
  {
    return "65fedc7a0cbfb8db035e46194a350bf1";
  }

  static const char* value(const ::iamech_ros::WPLC&) { return value(); }
};

template<>
struct DataType< ::iamech_ros::WPLC > {
  static const char* value()
  {
    return "iamech_ros/WPLC";
  }

  static const char* value(const ::iamech_ros::WPLC&) { return value(); }
};


// service_traits::MD5Sum< ::iamech_ros::WPLCRequest> should match
// service_traits::MD5Sum< ::iamech_ros::WPLC >
template<>
struct MD5Sum< ::iamech_ros::WPLCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::iamech_ros::WPLC >::value();
  }
  static const char* value(const ::iamech_ros::WPLCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::iamech_ros::WPLCRequest> should match
// service_traits::DataType< ::iamech_ros::WPLC >
template<>
struct DataType< ::iamech_ros::WPLCRequest>
{
  static const char* value()
  {
    return DataType< ::iamech_ros::WPLC >::value();
  }
  static const char* value(const ::iamech_ros::WPLCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::iamech_ros::WPLCResponse> should match
// service_traits::MD5Sum< ::iamech_ros::WPLC >
template<>
struct MD5Sum< ::iamech_ros::WPLCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::iamech_ros::WPLC >::value();
  }
  static const char* value(const ::iamech_ros::WPLCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::iamech_ros::WPLCResponse> should match
// service_traits::DataType< ::iamech_ros::WPLC >
template<>
struct DataType< ::iamech_ros::WPLCResponse>
{
  static const char* value()
  {
    return DataType< ::iamech_ros::WPLC >::value();
  }
  static const char* value(const ::iamech_ros::WPLCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IAMECH_ROS_MESSAGE_WPLC_H
